const CONNECT_TO_WEBSOCKET = 'CONNECT_TO_WEBSOCKET';
const WS_SUBSCRIBE_TO_TICKER = 'WS_SUBSCRIBE_TO_TICKER';
const WS_CONNECTED = 'WS_CONNECTED';
const WS_SUBSCRIPTION_SUCCESSFUL = 'WS_SUBSCRIPTION_SUCCESSFUL';
const WS_SUBSCRIPTION_UPDATE = 'WS_SUBSCRIPTION_UPDATE';

export default {
    CONNECT_TO_WEBSOCKET,
    WS_SUBSCRIBE_TO_TICKER,
    WS_CONNECTED,
    WS_SUBSCRIPTION_SUCCESSFUL,
    WS_SUBSCRIPTION_UPDATE,
}