const CONNECT_TO_WEBSOCKET = 'CONNECT_TO_WEBSOCKET';
const WS_SUBSCRIBE_TO_TICKER = 'WS_SUBSCRIBE_TO_TICKER';
const WS_CONNECTED = 'WS_CONNECTED';

export default {
    CONNECT_TO_WEBSOCKET,
    WS_SUBSCRIBE_TO_TICKER,
    WS_CONNECTED,
}